version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - ./server/db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - webnet
    depends_on:
      - adotcollector
  web:
    build: .
    image: fastapi-microservices:${IMAGE_VERSION}
    command: uvicorn server.app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/server
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - webnet
    env_file:
      - .env
  adotcollector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: ["--config=otel-local-config.yaml"]
    env_file:
      - .env
    volumes:
      - ./config-test.yaml:/otel-local-config.yaml
      - ~/.aws:/root/.aws
    networks:
      - webnet

networks:
  webnet:

volumes:
  postgres_data:  # Define the volume for PostgreSQL data