version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      WORKSHOP_POSTGRES_USER: ${WORKSHOP_POSTGRES_USER}
      WORKSHOP_POSTGRES_PASSWORD: ${WORKSHOP_POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      WORKSHOP_POSTGRES_DB: ${WORKSHOP_POSTGRES_DB}
    volumes:
      - ./.env:/.env
      - ./server/db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - webnet

  web:
    build: .
    image: fastapi-microservices:${IMAGE_VERSION}
    command: uvicorn server.app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/server
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - webnet
    environment: 
      - DATABASE_URL=${DOCKER_DATABASE_URL}

networks:
  webnet:

volumes:
  postgres_data:  # Define the volume for PostgreSQL data