extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: "us-east-1"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
      processors: [batch, memory_limiter]
  telemetry:
    logs:
      level: debug
